### ISSUE TITLE
ImportError: cannot import name '_api_types' from 'playwright._impl'

### ISSUE THREAD

**Issue by ZeALer** [3mora2/WPP_Whatsapp#27]
When I update to 0.1.5.2 there's an error message.

```
Traceback (most recent call last):
  File "C:\wa\kirim.py", line 1, in <module>
    from WPP_Whatsapp import Create
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\__init__.py", line 1, in <module>
    from WPP_Whatsapp.api.Whatsapp import Whatsapp
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\api\Whatsapp.py", line 4, in <module>
    from WPP_Whatsapp.api.layers.HostLayer import HostLayer
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\api\layers\HostLayer.py", line 11, in <module>
    from WPP_Whatsapp.PlaywrightSafeThread import ThreadsafeBrowser
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\PlaywrightSafeThread\__init__.py", line 1, in <module>
    from WPP_Whatsapp.PlaywrightSafeThread.browser.threadsafe_browser import Thr
eadsafeBrowser
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\PlaywrightSafeThread\browser\threadsafe_browser.py", line
11, in <module>
    from playwright._impl import _api_types
ImportError: cannot import name '_api_types' from 'playwright._impl' (C:\Users\A
dministrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwrigh
t\_impl\__init__.py)
```

Tried to use older version but still no success.

**Comment by 3mora2** [comment]
Update Now, it should work

**Comment by ZeALer** [comment]
New error comes up

```

Traceback (most recent call last):
  File "C:\wa\kirim.py", line 1, in <module>
    from WPP_Whatsapp import Create
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\__init__.py", line 1, in <module>
    from WPP_Whatsapp.api.Whatsapp import Whatsapp
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\api\Whatsapp.py", line 4, in <module>
    from WPP_Whatsapp.api.layers.HostLayer import HostLayer
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\api\layers\HostLayer.py", line 12, in <module>
    from WPP_Whatsapp.PlaywrightSafeThread import ThreadsafeBrowser
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\PlaywrightSafeThread\__init__.py", line 1, in <module>
    from WPP_Whatsapp.PlaywrightSafeThread.browser.threadsafe_browser import Thr
eadsafeBrowser
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\PlaywrightSafeThread\browser\threadsafe_browser.py", line
12, in <module>
    from playwright_stealth import stealth_async
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\playwright_stealth\__init__.py", line 2, in <module>
    from playwright_stealth.stealth import stealth_sync, stealth_async, StealthC
onfig
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\playwright_stealth\stealth.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

```

**Comment by 3mora2** [comment]
use firefox and install it
`creator = Create(session=your_session_name, browser="firefox", install=True)`

**Comment by ZeALer** [comment]
New error comes up

```

Downloading Firefox 119.0 (playwright build v1429) from https://playwright.azure
edge.net/builds/firefox/1429/firefox-win64.zip
80.5 Mb [====================] 100% 0.0s
Firefox 119.0 (playwright build v1429) downloaded to C:\Users\Administrator\AppD
ata\Local\ms-playwright\firefox-1429
Exception in thread Thread-1 (__thread_worker):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threa
ding.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threa
ding.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\PlaywrightSafeThread\browser\threadsafe_browser.py", line
335, in __thread_worker
    self.loop.run_until_complete(self.__start_playwright())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\async
io\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\WPP_Whatsapp\PlaywrightSafeThread\browser\threadsafe_browser.py", line
260, in __start_playwright
    self.context = await browser_type.launch_persistent_context(**self._browser_
persistent_option)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\playwright\async_api\_generated.py", line 14997, in launch_persistent_c
ontext
    await self._impl_obj.launch_persistent_context(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\playwright\_impl\_browser_type.py", line 158, in launch_persistent_cont
ext
    from_channel(await self._channel.send("launchPersistentContext", params)),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\playwright\_impl\_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\playwright\_impl\_connection.py", line 492, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-
packages\playwright\_impl\_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: spawn UNKNOWN

```

**Comment by ZeALer** [comment]
There's something wrong with my firefox. Using Edge and run smoothly

`
creator = Create(session=your_session_name, browser="msedge", install=True)
`

**Comment by 3mora2** [comment]
Error related to playwright when try launch profile saved before or create new one
